name: Build Basic Games Plugin

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-24.04 ]
        include:
          - os: windows-2022
            preset: vs2022-windows
            build_dir: vsbuild
          - os: ubuntu-24.04
            preset: linux
            build_dir: build

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set environmental variables
        shell: bash
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          path: build

      - name: Configure Basic Games Plugin build
        working-directory: ${{ github.workspace }}/build
        shell: pwsh
        run: |
          cmake --preset ${{ matrix.preset }} "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install" "-DVCPKG_MANIFEST_FEATURES=standalone"

      - name: Build Basic Games Plugin
        working-directory: ${{ github.workspace }}/build
        run: cmake --build ${{ matrix.build_dir }} --config RelWithDebInfo

      - name: Install Basic Games Plugin
        working-directory: ${{ github.workspace }}/build
        run: cmake --install ${{ matrix.build_dir }} --config RelWithDebInfo

      - name: Upload Basic Games Plugin artifact
        uses: actions/upload-artifact@master
        with:
          name: basic_games_${{ runner.os }}
          path: ${{ github.workspace }}/install/bin/plugins
